# Generated by Django 2.0 on 2019-02-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruser',
            name='password',
            field=models.CharField(default='', max_length=200, verbose_name='Password'),
        ),
    ]
