# Generated by Django 2.0 on 2019-02-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacheruser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruser',
            name='idcard',
            field=models.CharField(default='', max_length=200, verbose_name='ID Card'),
        ),
    ]
