# Generated by Django 2.0 on 2019-02-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dormadminuser',
            options={'ordering': ['-permission']},
        ),
    ]
