# Generated by Django 2.0 on 2019-02-16 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0006_student_teacher'),
        ('dormadmin', '0003_auto_20190216_1456'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dormadminuser',
            unique_together={('workid', 'incharge')},
        ),
    ]
