# Generated by Django 2.0 on 2019-02-15 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Building Number')),
                ('build_date', models.DateField(verbose_name='Build Date')),
                ('volume', models.IntegerField(verbose_name='Number of Rooms')),
                ('sex', models.CharField(max_length=100, verbose_name='Who lives here?')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Room Number')),
                ('volume', models.IntegerField(verbose_name='Room Volume')),
                ('free', models.IntegerField(verbose_name='Spare Bed')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dorm.Building', verbose_name='Building Number')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Student Name')),
                ('sex', models.CharField(max_length=10, verbose_name='Sex')),
                ('info', models.CharField(max_length=200, verbose_name='Student Info')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='dorm.Room', verbose_name='Room_number')),
            ],
        ),
    ]
