# Generated by Django 2.0 on 2019-02-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='building',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='Number of Floor'),
        ),
    ]
