# Generated by Django 2.0 on 2019-02-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0002_auto_20190216_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.CharField(default='', max_length=200, verbose_name='Student Number'),
        ),
    ]
