# Generated by Django 2.0 on 2019-02-16 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('dorm', '0005_auto_20190216_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='teacher.TeacherUser', verbose_name="Student's Teacher"),
        ),
    ]
