# Generated by Django 2.0 on 2019-02-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0006_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='idcard',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='ID Card'),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Student ID'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
    ]
